"""Acceptance research packet for the real 2026-09-19 SANSERA execution.

This is not a synthetic market-data fixture. It records evidence collected during
the manual web-research run used to validate Stage 4B. The packet is intentionally
company-specific and is only an acceptance sample for the execution engine.
"""

from __future__ import annotations

from datetime import date

from agent.contracts import Evidence, EvidenceKind, ResearchDomain, ResearchPlan, SourceTier
from agent.research_execution import (
    CausalFinding,
    ContradictionFinding,
    ResearchProviderPacket,
    evidence_ref,
)

CUTOFF = date(2026, 9, 18)
RETRIEVED = date(2026, 9, 19)


def sansera_plan() -> ResearchPlan:
    return ResearchPlan(
        symbol="SANSERA",
        company_archetype="precision engineering manufacturer transitioning from automotive ICE into higher-complexity automotive, aerospace, defence and semiconductor-equipment applications",
        economic_drivers=(
            "conversion of awarded precision-component programs into production revenue",
            "capacity, qualification and machine availability",
            "mix shift toward ADS, tech-agnostic and xEV products",
            "customer wallet share and concentration",
            "export geography, tariffs and FX",
            "input-cost pass-through and manufacturing efficiency",
            "capital allocation and incremental asset turns",
        ),
        material_domains=(
            ResearchDomain.FINANCIALS,
            ResearchDomain.MANAGEMENT,
            ResearchDomain.ORDERS,
            ResearchDomain.CAPACITY,
            ResearchDomain.CUSTOMERS_SUPPLIERS,
            ResearchDomain.PEERS,
            ResearchDomain.INDUSTRY,
            ResearchDomain.GOVERNMENT_REGULATION,
            ResearchDomain.INPUTS_ENERGY,
            ResearchDomain.FX,
            ResearchDomain.TARIFF_TRADE,
            ResearchDomain.MACRO_GEOPOLITICS,
            ResearchDomain.TECHNOLOGY_IP,
            ResearchDomain.CAPITAL_MARKETS,
            ResearchDomain.LEGAL_COMPLIANCE,
            ResearchDomain.SCHEDULED_EVENTS,
            ResearchDomain.MARKET_REACTION,
        ),
        hypotheses=(
            "Is the current diversification producing a durable improvement in revenue quality and margins?",
            "Can the reported order pipeline be converted into revenue without capacity, qualification or machine bottlenecks?",
            "Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
            "How does cross-border exposure change the economics under tariffs, FX and changing manufacturing footprints?",
            "Do capital investment and financial capacity support the growth plan without creating a balance-sheet or return-on-capital problem?",
        ),
        exclusions=(
            "generic headline collection without a company exposure mechanism",
            "target prices and valuation recommendations",
            "qualitative investment scoring",
            "recalculation of System-1 ranking or momentum",
        ),
    )


def sansera_evidence() -> tuple[Evidence, ...]:
    return (
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Q1FY27 revenue was INR 10,213 million, up 33.3% YoY; EBITDA was INR 1,961 million, up 48%, with 19.2% margin; PAT was INR 874 million, up 39%.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.FINANCIALS, materiality="high",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Non-auto revenue reached 20.8% of Q1FY27 sales and grew 129.9% YoY; ADS sales grew more than threefold, while Auto ICE still grew 20.8%.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.MANAGEMENT, materiality="high",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="The non-ADS new-business order book was INR 18,493 million at June 2026, defined as peak annual revenue from LOIs/POs whose production had started after 1-Apr-2026 or had not yet started, with peak annual revenue expected within three years.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.ORDERS, materiality="high",
            hypothesis="Can the reported order pipeline be converted into revenue without capacity, qualification or machine bottlenecks?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="ADS cumulative unexecuted backlog was INR 44,368 million at June 2026 and the presentation describes it as executable over approximately five years; Q1 ADS revenue was INR 1,454 million and FY27 ADS revenue guidance was INR 5,500-6,000 million.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.ORDERS, materiality="high",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="The company planned an 80,000 sq ft ADS hangar, a 45,000 sq ft defence plant, a surface-coating facility, additional xEV machining, Manesar expansion and Pantnagar forging capacity; management also stated it is building capacity ahead of demand and qualifications.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.CAPACITY, materiality="high",
            hypothesis="Can the reported order pipeline be converted into revenue without capacity, qualification or machine bottlenecks?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.NEGATIVE,
            claim="In the Q4FY26 earnings call, management said semiconductor customers were blocking machining capacity because of a volume surge, while mother-machine availability and lead time were the key execution constraint.",
            source="https://sansera.in/wp-content/uploads/2026/05/Earnings-Call-Transcript-Q4FY26.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 5, 28),
            event_date=date(2026, 5, 21), retrieved_on=RETRIEVED,
            domain=ResearchDomain.CAPACITY, materiality="high",
            hypothesis="Can the reported order pipeline be converted into revenue without capacity, qualification or machine bottlenecks?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="FY26 top-five customer concentration was 44.5%, down from 59.2% in FY21; the company also reported relationships with 23 key two-wheeler, 13 EV, 16 light-vehicle and 12 MHCV OEMs.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 3, 31), retrieved_on=RETRIEVED,
            domain=ResearchDomain.CUSTOMERS_SUPPLIERS, materiality="high",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.UNKNOWN,
            claim="Customer concentration within the ADS backlog itself was not disclosed in the reviewed Q1FY27 presentation; therefore the concentration of the five-year ADS backlog remains unresolved.",
            source="research-window: Q1FY27 presentation review",
            source_tier=SourceTier.DERIVED, retrieved_on=RETRIEVED,
            domain=ResearchDomain.CUSTOMERS_SUPPLIERS, materiality="high",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="FY26 customer and product mix shows connecting rods at 35.5%, rocker arms 15.1%, crankshaft assembly 14.1%, and aerospace products 9.6%; top-five customer share has been declining while aerospace mix has increased.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 3, 31), retrieved_on=RETRIEVED,
            domain=ResearchDomain.PEERS, materiality="high",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Bharat Forge reported a FY26 defence order book of INR 10,961 crore and is expanding aerospace and defence manufacturing, providing a relevant Indian precision-engineering comparison with broader non-auto exposure.",
            source="https://www.bharatforge.com/AR2026/operational-highlights.html",
            source_tier=SourceTier.PRIMARY,
            event_date=date(2026, 3, 31), retrieved_on=RETRIEVED,
            domain=ResearchDomain.PEERS, materiality="medium",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Happy Forgings reported a roughly INR 950 crore new-business order book over 2-3 years and added machining/heavy-forging capacity, showing that Indian precision-component peers are also expanding into higher-value industrial applications.",
            source="https://www.stockscans.in/company/NSE%3AHAPPYFORGE/transcript-notes/202603/o9u379s1w4g1dm24qb2vd90r.pdf",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 5, 28),
            event_date=date(2026, 5, 28), retrieved_on=RETRIEVED,
            domain=ResearchDomain.PEERS, materiality="medium",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="ACMA reports FY2025-26 Indian auto-component turnover of INR 7.59 lakh crore, 12.7% growth, OEM supplies growth of 16.3%, and exports of USD 24 billion, supporting a broad industry demand/localisation backdrop.",
            source="https://acma.in/about-us.php",
            source_tier=SourceTier.PRIMARY, event_date=date(2026, 3, 31), retrieved_on=RETRIEVED,
            domain=ResearchDomain.INDUSTRY, materiality="medium",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Airbus said global aircraft demand remains robust, forecasting around 42,000 new aircraft over 20 years and India demand of about 3,480 aircraft, while noting ongoing supply-chain challenges.",
            source="https://www.reuters.com/business/aerospace-defense/airbus-sees-no-softening-demand-despite-geopolitical-headwinds-2026-09-15/",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 9, 15),
            event_date=date(2026, 9, 15), retrieved_on=RETRIEVED,
            domain=ResearchDomain.INDUSTRY, materiality="medium",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.NEGATIVE,
            claim="Boeing reported that stabilising 737 MAX production at 47 aircraft per month was taking longer than expected because of supply-chain and certification issues, demonstrating that aerospace demand does not automatically equal near-term supplier revenue conversion.",
            source="https://www.reuters.com/legal/litigation/boeing-ceo-says-it-is-taking-longer-stabilize-737-max-output-2026-09-16/",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 9, 16),
            event_date=date(2026, 9, 16), retrieved_on=RETRIEVED,
            domain=ResearchDomain.INDUSTRY, materiality="high",
            hypothesis="Can the reported order pipeline be converted into revenue without capacity, qualification or machine bottlenecks?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="India's Defence Production Department notified a sixth Positive Indigenisation List covering 405 items with estimated business potential of INR 3,070 crore, including components and raw materials.",
            source="https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=2300723&lang=2&reg=48",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 18),
            event_date=date(2026, 8, 18), retrieved_on=RETRIEVED,
            domain=ResearchDomain.GOVERNMENT_REGULATION, materiality="medium",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="India's draft DAP 2026 proposes higher indigenous content in the Buy Indian-IDDM category, while the government reports increasing defence production and domestic procurement.",
            source="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2227775&lang=3&reg=3",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 2, 13),
            event_date=date(2026, 2, 13), retrieved_on=RETRIEVED,
            domain=ResearchDomain.GOVERNMENT_REGULATION, materiality="medium",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Sansera's FY2024-25 annual report stated that raw-material cost fluctuations were fully passed through across domestic and international ICE businesses, supporting historical pricing resilience.",
            source="https://sansera.in/wp-content/uploads/2025/08/Annual-Report-2024-25.pdf",
            source_tier=SourceTier.PRIMARY,
            event_date=date(2025, 3, 31), retrieved_on=RETRIEVED,
            domain=ResearchDomain.INPUTS_ENERGY, materiality="high",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.UNKNOWN,
            claim="Current Q1FY27 disclosure identifies power and fuel inside cost of goods sold but does not provide a current segment-level sensitivity or contract-lag schedule sufficient to quantify the next-quarter input-cost effect.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.INPUTS_ENERGY, materiality="medium",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.UNKNOWN,
            claim="Historical company disclosure confirms foreign-currency exposure and use of forward contracts, but a current Q1FY27 net currency sensitivity was not established in the reviewed primary documents.",
            source="https://sansera.in/wp-content/uploads/2024/10/Placement-Document-15-10-2024.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2024, 10, 15),
            event_date=date(2024, 10, 15), retrieved_on=RETRIEVED,
            domain=ResearchDomain.FX, materiality="medium",
            hypothesis="How does cross-border exposure change the economics under tariffs, FX and changing manufacturing footprints?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.NEGATIVE,
            claim="Q1FY27 included an INR 126-129 million U.S. import-duty/tariff cost in reported expenses, and management said tariff uncertainty had delayed the planned U.S. connecting-rod facility.",
            source="https://earningscalls.dev/transcripts/sansera-engineering-limited_sansera_earnings_call_transcript_2026-08-13",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 8, 13),
            event_date=date(2026, 8, 13), retrieved_on=RETRIEVED,
            domain=ResearchDomain.TARIFF_TRADE, materiality="high",
            hypothesis="How does cross-border exposure change the economics under tariffs, FX and changing manufacturing footprints?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Management also said tariff uncertainty was prompting some customers to source more from Sansera's India operations as a stop-gap, showing that the same trade disruption can create both cost and sourcing-shift channels.",
            source="https://earningscalls.dev/transcripts/sansera-engineering-limited_sansera_earnings_call_transcript_2026-08-13",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 8, 13),
            event_date=date(2026, 8, 13), retrieved_on=RETRIEVED,
            domain=ResearchDomain.TARIFF_TRADE, materiality="high",
            hypothesis="How does cross-border exposure change the economics under tariffs, FX and changing manufacturing footprints?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.NEGATIVE,
            claim="On 18-Sep-2026 Reuters reported that new U.S. legislation gives the President authority to impose tariffs of up to 100% on imports from countries purchasing Russian oil or gas; India is among the countries that could be affected. The company-specific product incidence remains unresolved.",
            source="https://www.reuters.com/world/us/russia-sanctions-bill-gives-trump-sweeping-new-tariff-powers-2026-09-18/",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 9, 18),
            event_date=date(2026, 9, 18), retrieved_on=RETRIEVED,
            domain=ResearchDomain.MACRO_GEOPOLITICS, materiality="medium",
            hypothesis="How does cross-border exposure change the economics under tariffs, FX and changing manufacturing footprints?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Applied Materials announced a planned USD 5 billion India investment over the next decade amid strong AI-driven semiconductor demand and global supply-chain diversification; this is an industry backdrop relevant to Sansera's semiconductor-equipment component activity.",
            source="https://www.reuters.com/world/asia-pacific/applied-materials-invest-5-billion-india-modis-flagship-chip-event-kicks-off-2026-09-17/",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 9, 17),
            event_date=date(2026, 9, 17), retrieved_on=RETRIEVED,
            domain=ResearchDomain.TECHNOLOGY_IP, materiality="medium",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Sansera's Q1FY27 presentation describes semiconductor-equipment capabilities, a clean-room manufacturing setup, and order-driven radar/defence development partnerships; it also records the 60:40 Nichidai JV and INR 500 million planned Sansera investment.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.TECHNOLOGY_IP, materiality="high",
            hypothesis="Do capital investment and financial capacity support the growth plan without creating a balance-sheet or return-on-capital problem?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="ICRA reaffirmed Sansera at [ICRA]AA (Stable) for term loans and [ICRA]A1+ for short-term facilities; ICRA also noted that INR 1,200 crore QIP proceeds had largely been used to repay/prepay borrowings.",
            source="https://www.icra.in/Rating/GetRationalReportFilePdf?Id=140552",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 1, 28),
            event_date=date(2026, 1, 28), retrieved_on=RETRIEVED,
            domain=ResearchDomain.CAPITAL_MARKETS, materiality="high",
            hypothesis="Do capital investment and financial capacity support the growth plan without creating a balance-sheet or return-on-capital problem?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="FY26 capex was INR 5,097 million and Q1FY27 capex was INR 1,342 million; management's stated incremental asset-turn targets are 2.0-2.2x for ADS and 1.25-1.3x for Auto ICE.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.CAPITAL_MARKETS, materiality="high",
            hypothesis="Do capital investment and financial capacity support the growth plan without creating a balance-sheet or return-on-capital problem?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.NEGATIVE,
            claim="Q1FY27 recognised INR 169 million for settlement of a U.S. District Court litigation matter; the company states it settled without admission of liability and expects substantial insurance coverage.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 6, 30), retrieved_on=RETRIEVED,
            domain=ResearchDomain.LEGAL_COMPLIANCE, materiality="medium",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.UNKNOWN,
            claim="The reviewed primary Q1FY27 materials did not establish a recurring systemic quality, litigation or regulatory problem beyond the disclosed settled matter.",
            source="research-window: Q1FY27 primary-document review",
            source_tier=SourceTier.DERIVED, retrieved_on=RETRIEVED,
            domain=ResearchDomain.LEGAL_COMPLIANCE, materiality="medium",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="A post-quarter update reported the ADS backlog at approximately INR 57.5 billion, up from INR 44.368 billion at June-end; the newer figure is reported as executable over five years and reflects subsequent order additions.",
            source="https://foliopulse.in/stock/SANSERA",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 8, 20),
            event_date=date(2026, 8, 20), retrieved_on=RETRIEVED,
            domain=ResearchDomain.ORDERS, materiality="high",
            hypothesis="Can the reported order pipeline be converted into revenue without capacity, qualification or machine bottlenecks?",
            notes="Secondary-source figure; underlying primary transcript should be retained/checked before treating the exact 57.5bn figure as canonical.",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.NEGATIVE,
            claim="A summary of the FY2025-26 annual-report disclosures reports a historical employee-misappropriation/fraud matter at the standalone entity, with recovery proceedings underway; the amount reported in the summary is about INR 1.22 crore.",
            source="https://www.whalesbook.com/company/announcements/SANSERA",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 9, 2),
            event_date=date(2026, 9, 2), retrieved_on=RETRIEVED,
            domain=ResearchDomain.LEGAL_COMPLIANCE, materiality="medium",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
            notes="Secondary summary of the FY2025-26 annual report; underlying annual report should be reviewed directly before treating the exact amount/status as final.",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="A market-reporting source recorded a roughly 6% share-price rise to a 52-week high after the Q1FY27 results, indicating strong immediate market reaction to the reported growth and ADS narrative.",
            source="https://www.timesofwhales.com/news/English/industrial-goodsservices/Sansera-Engineering-Hits-52-Week-High-on-Q1-Growth/6a7e9f9d6ffbe1e6461ac21e",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 8, 14),
            event_date=date(2026, 8, 14), retrieved_on=RETRIEVED,
            domain=ResearchDomain.MARKET_REACTION, materiality="medium",
            hypothesis="Is the current diversification producing a durable improvement in revenue quality and margins?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="Sansera appointed Hari Krishnan as Executive Director & CEO of ADS effective 12-Aug-2026 for five years, subject to shareholder approval; this aligns dedicated leadership with the rapidly expanding ADS segment.",
            source="https://sansera.in/wp-content/uploads/2026/08/Investors-presentation-Q1FY27.pdf",
            source_tier=SourceTier.PRIMARY, published_on=date(2026, 8, 12),
            event_date=date(2026, 8, 12), retrieved_on=RETRIEVED,
            domain=ResearchDomain.MANAGEMENT, materiality="medium",
            hypothesis="Is ADS growth structurally durable, or is the current backlog concentrated in a small number of customers and execution programs?",
        ),
        Evidence(
            entity="SANSERA", kind=EvidenceKind.POSITIVE,
            claim="The company disclosed an AGM scheduled for 24-Sep-2026 in its Q1FY27 result materials/filing trail; shareholder approval is relevant to the new ADS CEO appointment and board redesignations.",
            source="https://foliopulse.in/stock/SANSERA",
            source_tier=SourceTier.SECONDARY, published_on=date(2026, 8, 24),
            event_date=date(2026, 9, 24), retrieved_on=RETRIEVED,
            domain=ResearchDomain.SCHEDULED_EVENTS, materiality="medium",
            hypothesis="Do capital investment and financial capacity support the growth plan without creating a balance-sheet or return-on-capital problem?",
        ),
    )


def sansera_packet() -> ResearchProviderPacket:
    evidence = sansera_evidence()
    refs = {e.claim: evidence_ref(e) for e in evidence}

    return ResearchProviderPacket(
        plan=sansera_plan(),
        evidence=evidence,
        causal_findings=(
            CausalFinding(
                hypothesis=sansera_plan().hypotheses[0],
                finding="Diversification is already visible in reported revenue, not only in announcements: non-auto reached 20.8% of Q1 sales while Auto ICE still grew 20.8%, and consolidated EBITDA margin rose to 19.2%.",
                mechanism="Faster-growing ADS/non-auto and tech-agnostic/xEV businesses are changing mix while the legacy automotive base continues to generate growth and cash.",
                timing="Already visible in Q1FY27; durability depends on multi-quarter conversion of the order pipeline and sustained margins.",
                uncertainty="The presentation does not provide enough current segment-level margin detail to isolate how much of the margin change is mix versus operating leverage or other factors.",
                evidence_refs=(refs["Q1FY27 revenue was INR 10,213 million, up 33.3% YoY; EBITDA was INR 1,961 million, up 48%, with 19.2% margin; PAT was INR 874 million, up 39%."],
                               refs["Non-auto revenue reached 20.8% of Q1FY27 sales and grew 129.9% YoY; ADS sales grew more than threefold, while Auto ICE still grew 20.8%."]),
            ),
            CausalFinding(
                hypothesis=sansera_plan().hypotheses[1],
                finding="The order pipeline is substantial but conversion is explicitly capacity-gated rather than equivalent to near-term revenue.",
                mechanism="LOI/PO → qualification/production → capacity availability → machine commissioning → customer ramp → revenue. Semiconductor machining demand is already competing for mother-machine capacity.",
                timing="Non-ADS peak annual revenue is expected to mature within three years; ADS backlog is described as executable over about five years.",
                uncertainty="Current utilisation, exact qualification status and machine-by-machine bottlenecks are not fully disclosed.",
                evidence_refs=(refs["The non-ADS new-business order book was INR 18,493 million at June 2026, defined as peak annual revenue from LOIs/POs whose production had started after 1-Apr-2026 or had not yet started, with peak annual revenue expected within three years."],
                               refs["The company planned an 80,000 sq ft ADS hangar, a 45,000 sq ft defence plant, a surface-coating facility, additional xEV machining, Manesar expansion and Pantnagar forging capacity; management also stated it is building capacity ahead of demand and qualifications."],
                               refs["In the Q4FY26 earnings call, management said semiconductor customers were blocking machining capacity because of a volume surge, while mother-machine availability and lead time were the key execution constraint."]),
            ),
            CausalFinding(
                hypothesis=sansera_plan().hypotheses[2],
                finding="ADS demand has multiple external supports and existing revenue, but backlog concentration and customer-specific qualification exposure remain unresolved.",
                mechanism="Aerospace demand, semiconductor equipment investment and defence indigenisation create demand pools; Sansera must convert those pools through customer qualification, machine availability and program ramp.",
                timing="ADS revenue is already 14.2% of Q1FY27 sales; backlog extends over several years.",
                uncertainty="The company has not disclosed ADS backlog concentration by customer or the precise proportion already qualified for production.",
                evidence_refs=(refs["ADS cumulative unexecuted backlog was INR 44,368 million at June 2026 and the presentation describes it as executable over approximately five years; Q1 ADS revenue was INR 1,454 million and FY27 ADS revenue guidance was INR 5,500-6,000 million."],
                               refs["Customer concentration within the ADS backlog itself was not disclosed in the reviewed Q1FY27 presentation; therefore the concentration of the five-year ADS backlog remains unresolved."],
                               refs["India's Defence Production Department notified a sixth Positive Indigenisation List covering 405 items with estimated business potential of INR 3,070 crore, including components and raw materials."]),
            ),
            CausalFinding(
                hypothesis=sansera_plan().hypotheses[3],
                finding="Cross-border exposure creates a two-sided mechanism: tariffs impose direct cost and can delay localisation decisions, but they can also encourage customers to source more from India's existing facilities.",
                mechanism="Tariff policy → landed-cost difference → customer sourcing decision → Sansera export mix → facility-location economics. The company's planned U.S. facility is part of this decision tree.",
                timing="A direct Q1FY27 tariff/import-duty cost was already recognised; broader U.S. tariff authority remains a future policy risk as of the 18-Sep cutoff.",
                uncertainty="Product-specific tariff classification, customer pass-through and the ultimate incidence of any new U.S. tariff on Sansera products are unresolved.",
                evidence_refs=(refs["Q1FY27 included an INR 126-129 million U.S. import-duty/tariff cost in reported expenses, and management said tariff uncertainty had delayed the planned U.S. connecting-rod facility."],
                               refs["Management also said tariff uncertainty was prompting some customers to source more from Sansera's India operations as a stop-gap, showing that the same trade disruption can create both cost and sourcing-shift channels."],
                               refs["On 18-Sep-2026 Reuters reported that new U.S. legislation gives the President authority to impose tariffs of up to 100% on imports from countries purchasing Russian oil or gas; India is among the countries that could be affected. The company-specific product incidence remains unresolved."]),
            ),
            CausalFinding(
                hypothesis=sansera_plan().hypotheses[4],
                finding="The balance sheet and prior QIP provide funding capacity for the current capex program, while management targets higher asset turns for ADS than Auto ICE.",
                mechanism="QIP deleveraging → stronger balance sheet → ability to fund growth capex → asset commissioning → revenue ramp. Higher targeted ADS asset turns would improve capital productivity if achieved.",
                timing="Capex is already underway; the key test is commissioning and utilisation rather than funding availability alone.",
                uncertainty="Actual incremental ROCE by new facility and realised ADS asset turns are future observations, not current facts.",
                evidence_refs=(refs["ICRA reaffirmed Sansera at [ICRA]AA (Stable) for term loans and [ICRA]A1+ for short-term facilities; ICRA also noted that INR 1,200 crore QIP proceeds had largely been used to repay/prepay borrowings."],
                               refs["FY26 capex was INR 5,097 million and Q1FY27 capex was INR 1,342 million; management's stated incremental asset-turn targets are 2.0-2.2x for ADS and 1.25-1.3x for Auto ICE."]),
            ),
        ),
        contradictions=(
            ContradictionFinding(
                hypothesis=sansera_plan().hypotheses[1],
                original_claim="Large order books provide revenue visibility.",
                counter_evidence="Semiconductor mother-machine lead times and new facility commissioning can constrain conversion.",
                resolution="Treat backlog as multi-year opportunity, not as equivalent near-term revenue; monitor capacity commissioning and utilisation.",
                evidence_refs=(refs["ADS cumulative unexecuted backlog was INR 44,368 million at June 2026 and the presentation describes it as executable over approximately five years; Q1 ADS revenue was INR 1,454 million and FY27 ADS revenue guidance was INR 5,500-6,000 million."],
                               refs["In the Q4FY26 earnings call, management said semiconductor customers were blocking machining capacity because of a volume surge, while mother-machine availability and lead time were the key execution constraint."]),
            ),
            ContradictionFinding(
                hypothesis=sansera_plan().hypotheses[2],
                original_claim="ADS is supported by strong aerospace, semiconductor and defence demand.",
                counter_evidence="Boeing production stabilisation is taking longer than expected and customer concentration within ADS backlog is unresolved.",
                resolution="Industry demand supports the opportunity, but company revenue timing remains dependent on specific program execution and customer concentration.",
                evidence_refs=(refs["Airbus said global aircraft demand remains robust, forecasting around 42,000 new aircraft over 20 years and India demand of about 3,480 aircraft, while noting ongoing supply-chain challenges."],
                               refs["Boeing reported that stabilising 737 MAX production at 47 aircraft per month was taking longer than expected because of supply-chain and certification issues, demonstrating that aerospace demand does not automatically equal near-term supplier revenue conversion."],
                               refs["Customer concentration within the ADS backlog itself was not disclosed in the reviewed Q1FY27 presentation; therefore the concentration of the five-year ADS backlog remains unresolved."]),
            ),
            ContradictionFinding(
                hypothesis=sansera_plan().hypotheses[3],
                original_claim="Tariffs may increase demand for India sourcing.",
                counter_evidence="Sansera already recognised tariff cost and delayed its U.S. facility because of tariff uncertainty.",
                resolution="Tariff effects are asymmetric: near-term cost and localisation uncertainty coexist with potential India-sourcing gains. Net effect is not resolved.",
                evidence_refs=(refs["Q1FY27 included an INR 126-129 million U.S. import-duty/tariff cost in reported expenses, and management said tariff uncertainty had delayed the planned U.S. connecting-rod facility."],
                               refs["Management also said tariff uncertainty was prompting some customers to source more from Sansera's India operations as a stop-gap, showing that the same trade disruption can create both cost and sourcing-shift channels."]),
            ),
            ContradictionFinding(
                hypothesis=sansera_plan().hypotheses[0],
                original_claim="Diversification is reducing concentration risk.",
                counter_evidence="Connecting rods still represented 35.5% of FY26 product sales, so product-level concentration remains material even as end-market mix diversifies.",
                resolution="End-market diversification is real, but product concentration has not disappeared; both dimensions must be monitored.",
                evidence_refs=(refs["FY26 customer and product mix shows connecting rods at 35.5%, rocker arms 15.1%, crankshaft assembly 14.1%, and aerospace products 9.6%; top-five customer share has been declining while aerospace mix has increased."]),
            ),
        ),
        unresolved_questions=(
            "What percentage of the ADS backlog is concentrated in the largest customers/programs?",
            "Which ADS programs are fully qualified for serial production versus still in qualification?",
            "What is current plant and machine utilisation by major ADS facility?",
            "What is the current contract-level tariff pass-through and customer incidence by U.S.-bound product?",
            "What is current net FX sensitivity after natural hedges and forwards?",
            "What incremental ROCE is being achieved as the new ADS capacity is commissioned?",
        ),
        monitoring_questions=(
            "Track ADS revenue versus the five-year backlog and FY27 guidance.",
            "Track mother-machine arrivals, commissioning and ADS utilisation.",
            "Track U.S. tariff incidence, U.S. facility timing and India-to-U.S. export mix.",
            "Track top-customer/backlog concentration if disclosed in future filings.",
            "Track ADS margin versus consolidated margin and stated 25-30% mature target.",
            "Track capex versus commissioning and realised asset turns.",
            "Track AGM approval and subsequent management/board changes.",
        ),
    )
